/**
 * #198: the world map screen's art, painted by the map painter (#188, tools/art/map.ts) from the world data (src/config/world.ts) and
 * rendered by `npm run art` into public/sprites/world-map.png (every realm open, with its roads, flags, castles and name ribbon) and
 * public/sprites/world-clouds.png (a band per realm in REALM_IDS order: the clouds the painter puts over that realm when it alone is
 * sealed, transparent elsewhere), plus src/ui/world-map.css that places each realm's clouds and hit area. The screen stacks the clouds
 * of the realms still shut over the open map, so any mix of open realms needs no repaint. The names are set on top in Cinzel.
 */
import { REALM_IDS, REALMS, type RealmId } from '../../../src/config/world';
import { type MapLayout, paintMap, type RealmLayout, type Terrain, trail } from '../map';
import { png } from '../png';

export const worldPaths = { map: 'public/sprites/world-map.png', clouds: 'public/sprites/world-clouds.png', css: 'src/ui/world-map.css' };

/** Where each realm sits, by ring from the bottom (the Marches) to the top (the Last Bastion), as in the painter's sample world. */
const PLACE: Record<RealmId, { terrain: Terrain; rect: RealmLayout['rect']; flip?: true }> = {
  marches: { terrain: 'marches', rect: [0, 450, 960, 150] },
  ironHold: { terrain: 'steel', rect: [0, 300, 320, 150], flip: true },
  barrowvale: { terrain: 'grave', rect: [320, 300, 320, 150], flip: true },
  cinderlands: { terrain: 'flame', rect: [640, 300, 320, 150], flip: true },
  frozenPass: { terrain: 'frost', rect: [0, 150, 480, 150] },
  stormspire: { terrain: 'storm', rect: [480, 150, 480, 150] },
  hallowedReach: { terrain: 'holy', rect: [0, 0, 330, 150], flip: true },
  lastBastion: { terrain: 'bastion', rect: [330, 0, 300, 150] },
  crimsonFields: { terrain: 'blood', rect: [630, 0, 330, 150], flip: true },
};
const W = 960, H = 600;
const at = (id: RealmId) => REALM_IDS.indexOf(id);

function layout(sealed?: RealmId): MapLayout {
  return {
    w: W, h: H, seed: 198, names: false,
    realms: REALM_IDS.map((id) => {
      const p = PLACE[id], n = REALMS[id].levels.length;
      const points = n === 1 ? [{ x: p.rect[0] + p.rect[2] / 2, y: p.rect[1] + 118, n: 1, castle: true }] : trail(p.rect, n, [], p.flip);
      return { terrain: p.terrain, name: REALMS[id].name, rect: p.rect, points, sealed: id === sealed };
    }),
    // the roads between realms: the Marches up into ring 2, on through ring 3 to ring 4 and the Last Bastion
    links: [[at('marches'), at('cinderlands')], [at('cinderlands'), at('barrowvale')], [at('barrowvale'), at('ironHold')], [at('ironHold'), at('frozenPass')], [at('frozenPass'), at('stormspire')], [at('frozenPass'), at('hallowedReach')], [at('stormspire'), at('crimsonFields')], [at('crimsonFields'), at('lastBastion')]],
  };
}

const pct = (n: number) => `${+(n * 100).toFixed(4)}%`;

export function buildWorld(): { map: Buffer; clouds: Buffer; css: string } {
  const lay = layout();
  const open = paintMap(lay).rgba;
  // Each realm's clouds: the pixels that change when it alone is sealed, cut to the rows they touch.
  const bands = REALM_IDS.map((id) => {
    const shut = paintMap(layout(id)).rgba;
    let y0 = H, y1 = 0;
    const px = new Uint8Array(W * H * 4);
    for (let i = 0; i < W * H; i++) {
      const o = i * 4;
      if (shut[o] === open[o] && shut[o + 1] === open[o + 1] && shut[o + 2] === open[o + 2]) continue;
      px.set(shut.subarray(o, o + 4), o);
      const y = Math.floor(i / W);
      y0 = Math.min(y0, y);
      y1 = Math.max(y1, y + 1);
    }
    if (y1 <= y0) y0 = y1 = 0; // nothing to cover (never, but keep the sheet well formed)
    return { id, y0, h: y1 - y0, px: px.subarray(y0 * W * 4, y1 * W * 4) };
  });
  const sheetH = bands.reduce((s, b) => s + b.h, 0);
  const sheet = new Uint8Array(W * sheetH * 4);
  const css = ['/* Generated by `npm run art` from tools/art/ui/world.ts (#198): do not edit. */',
    `.wm-map { aspect-ratio: ${W} / ${H}; background: url('/sprites/world-map.png') center / 100% 100% no-repeat; image-rendering: pixelated; }`,
    ".rr-land { background: url('/sprites/world-map.png') no-repeat; image-rendering: pixelated; }",
    ".wm-cloud { position: absolute; left: 0; width: 100%; background: url('/sprites/world-clouds.png') no-repeat; image-rendering: pixelated; pointer-events: none; }"];
  let y = 0;
  for (const b of bands) {
    sheet.set(b.px, y * W * 4);
    const r = PLACE[b.id].rect;
    css.push(`.wm-cloud.r-${b.id} { top: ${pct(b.y0 / H)}; height: ${pct(b.h / H)}; background-size: 100% ${pct(sheetH / Math.max(1, b.h))}; background-position: 0 ${sheetH === b.h ? '0' : pct(y / (sheetH - b.h))}; }`);
    css.push(`.wm-realm.r-${b.id} { left: ${pct(r[0] / W)}; top: ${pct(r[1] / H)}; width: ${pct(r[2] / W)}; height: ${pct(r[3] / H)}; }`);
    // #199: the realm road is this realm's part of the same map, its flags the painter's level points
    css.push(`.rr-land.r-${b.id} { aspect-ratio: ${r[2]} / ${r[3]}; --ar: ${+(r[2] / r[3]).toFixed(4)}; background-size: ${pct(W / r[2])} ${pct(H / r[3])}; background-position: ${r[2] === W ? '0' : pct(r[0] / (W - r[2]))} ${r[3] === H ? '0' : pct(r[1] / (H - r[3]))}; }`);
    for (const pt of lay.realms[at(b.id)].points) css.push(`.rr-flag.r-${b.id}.l-${pt.n} { left: ${pct((pt.x - r[0]) / r[2])}; top: ${pct((pt.y - r[1]) / r[3])}; }`);
    y += b.h;
  }
  return { map: png(W, H, open), clouds: png(W, sheetH, sheet), css: css.join('\n') + '\n' };
}
